[masters]
k8s-master ansible_host=10.32.11.52 node_ip=10.32.11.52 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[workers]
k8s-worker1 ansible_host=10.32.11.53 node_ip=10.32.11.53 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
k8s-worker2 ansible_host=10.32.11.54 node_ip=10.32.11.54 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[k8s_cluster:children]
masters
workers

[k8s_cluster:vars]
k8s_version=1.28.2
pod_network_cidr=10.244.0.0/16
service_subnet=10.96.0.0/12
metallb_ip_range="10.32.11.60-10.32.11.75"
