---
- hosts: masters
  become: yes
  tasks:
    - name: Install Tigera Operator via Helm
      kubernetes.core.helm:
        name: tigera-operator
        chart_ref: tigera-operator
        chart_repo_url: https://docs.tigera.io/calico/charts
        release_namespace: tigera-operator
        create_namespace: true
        release_state: present
        wait: true

    - name: Create Calico Installation CR
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operator.tigera.io/v1
          kind: Installation
          metadata:
            name: default
          spec:
            calicoNetwork:
              bgp: Disabled
              ipPools:
                - cidr: "{{ pod_network_cidr }}"
                  encapsulation: VXLANCrossSubnet
                  natOutgoing: Enabled
                  nodeSelector: all()