---
- hosts: masters
  become: yes
  tasks:
    - name: Download helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        mode: '0700'
        dest: /tmp/install_helm.sh

    - name: Install helm
      environment:
        DESIRED_VERSION: v3.19.0
      command: /tmp/install_helm.sh